const moves = {
  "Spiritual Pressure": {
    name: "Spiritual Pressure",
    type: "soul",
    attack: "status",
    power: 0,
  },
  "Sword Slash": {
    name: "Sword Slash",
    type: "neutral",
    attack: "physical",
    power: 30,
  },
  "Blade Surge": {
    name: "Blade Surge",
    type: "neutral",
    attack: "physical",
    power: 40,
  },
  "Sword Slam": {
    name: "Sword Slam",
    type: "neutral",
    attack: "physical",
    power: 40,
  },
  "Lunge": {
    name: "Lunge",
    type: "neutral",
    attack: "status",
    power: 0,
  },
  "Moon Fang Slash": {
    name: "Moon Fang Slash",
    type: "dark",
    attack: "special",
    power: 65,
  },
  "Moon Fang Barrage": {
    name: "Moon Fang Barrage",
    type: "dark",
    attack: "special",
    power: 55,
  },
  "Menacing Aura": {
    name: "Menacing Aura",
    type: "dark",
    attack: "status",
    power: 0,
  },
  "Cut Down": {
    name: "Cut Down",
    type: "dark",
    attack: "physical",
    power: 40,
  },
  "Heavenly Flame": {
    name: "Heavenly Flame",
    type: "fire",
    attack: "psychic",
    power: 0,
  },
  "Electric Strike Spear": {
    name: "Rubber Balloon",
    type: "lightning",
    attack: "special",
    power: 0,
  },
  "Pheonix Fire Bomb": {
    name: "Pheonix Fire Bomb",
    type: "fire",
    attack: "physical",
    power: 70,
  },
  "Vengeful Illusion": {
    name: "Vengeful Illusion",
    type: "dark",
    attack: "status",
    power: 0,
  },
  "Electric Strike": {
    name: "Electric Strike",
    type: "lightning",
    attack: "physical",
    power: 60,
  },
  "Tiger's Barrage": {
    name: "Tiger's Barrage",
    type: "neutral",
    attack: "physical",
    power: 45,
  },
  "Fireball": {
    name: "Fireball",
    type: "fire",
    attack: "special",
    power: 50,
  },
  "Kunai Barrage": {
    name: "Kunai Barrage",
    type: "neutral",
    attack: "physical",
    power: 45,
  },
  "Drain Life": {
    name: "Drain Life",
    type: "psychic",
    attack: "physical",
    power: 60,
  },
  "Vanishing Blow": {
    name: "Vanishing Blow",
    type: "neutral",
    attack: "physical",
    power: 45,
  },
  "Solar Flare": {
    name: "Solar Flare",
    type: "light",
    attack: "status",
    power: 0,
  },
  "Demon Elbow": {
    name: "Demon Elbow",
    type: "demon",
    attack: "physical",
    power: 70,
  },
  "Limb Regrowth": {
    name: "Limb Regrowth",
    type: "nature",
    attack: "status",
    power: 0,
  },
  "Angry Explosion": {
    name: "Angry Explosion",
    type: "psychic",
    attack: "special",
    power: 50,
  },
  "Rest": {
    name: "Rest",
    type: "neutral",
    attack: "status",
    power: 0,
  },
  "Candy Beam": {
    name: "Candy Beam",
    type: "psychic",
    attack: "status",
    power: 0,
  },
  "Psychic Blast": {
    name: "Psychic Blast",
    type: "psychic",
    attack: "special",
    power: 40,
  },
  "Energy Charge": {
    name: "Energy Charge",
    type: "neutral",
    attack: "status",
    power: 0,
  },
  "Rubber Balloon": {
    name: "Rubber Balloon",
    type: "neutral",
    attack: "status",
    power: 0,
  },
  "Punch": {
    name: "Punch",
    type: "neutral",
    attack: "physical",
    power: 35,
  },
  "Rapid Punches": {
    name: "Rapid Punches",
    type: "fighting",
    attack: "physical",
    power: 35,
  },
  "Rubber Pistol": {
    name: "Rubber Pistol",
    type: "fighting",
    attack: "physical",
    power: 35,
  },
  "Fighting Spirit": {
    name: "Fighting Spirit",
    type: "fighting",
    attack: "status",
    power: 0,
  },
  "Bazooka": {
    name: "Bazooka",
    type: "fighting",
    attack: "physical",
    power: 65,
  },
  "Phase Two": {
    name: "Phase Two",
    type: "neutral",
    attack: "status",
    power: 0,
  },
  "Headbutt": {
    name: "Headbutt",
    type: "neutral",
    attack: "physical",
    power: 40,
  },
  "Armament": {
    name: "Armament",
    type: "fighting",
    attack: "status",
    power: 0,
  },
  "Energy Blast": {
    name: "Energy Blast",
    type: "neutral",
    attack: "special",
    power: 25,
  }
};