const moves = {
  "Galaxy Cannon": {
    name: "Galaxy Cannon",
    type: "fighting",
    attack: "special",
    power: 75,
    accuracy: 100,
  },
  "Galaxy Burst": {
    name: "Galaxy Burst",
    type: "fighting",
    attack: "physical",
    power: 70,
    accuracy: 100,
  },
  "Energy Beam": {
    name: "Energy Beam",
    type: "neutral",
    attack: "special",
    power: 60,
    accuracy: 100,
  },
  "Dirty Fireworks": {
    name: "Dirty Fireworks",
    type: "fighting",
    attack: "physical",
    power: 55,
    accuracy: 100,
  },
  "Divine Bomb": {
    name: "Divine Bomb",
    type: "light",
    attack: "special",
    power: 250,
    accuracy: 100,
  },
  "Meteor Combo": {
    name: "Meteor Combo",
    type: "fighting",
    attack: "physical",
    power: 75,
    accuracy: 100,
  },
  "Super Energy Wave": {
    name: "Super Energy Wave",
    type: "fighting",
    attack: "special",
    power: 60,
    accuracy: 100,
  },
  "Cyclone Throw": {
    name: "Cyclone Throw",
    type: "fighting",
    attack: "physical",
    power: 50,
    accuracy: 100,
  },
  "Energy Wave": {
    name: "Energy Wave",
    type: "fighting",
    attack: "special",
    power: 40,
    accuracy: 100,
  },
  "Guzzle": {
    name: "Guzzle",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Reverse Lily": {
    name: "Reverse Lily",
    type: "fighting",
    attack: "physical",
    power: 100,
    accuracy: 100,
  },
  "Dive Kick": {
    name: "Dive Kick",
    type: "fighting",
    attack: "physical",
    power: 50,
    accuracy: 85,
  },
  "Afterimage": {
    name: "Afterimage",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 0,
  },
  "Sand Arm": {
    name: "Sand Arm",
    type: "demon",
    attack: "physical",
    power: 70,
    accuracy: 100,
  },
  "Substitution": {
    name: "Substitution",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Sand Bomb": {
    name: "Sand Bomb",
    type: "earth",
    attack: "special",
    power: 65,
    accuracy: 100,
  },
  "Sand Burial": {
    name: "Sand Burial",
    type: "earth",
    attack: "special",
    power: 60,
    accuracy: 70,
  },
  "Sand Storm": {
    name: "Sand Storm",
    type: "earth",
    attack: "special",
    power: 0,
    accuracy: 100,
  },
  "Sand Tsunami": {
    name: "Sand Tsunami",
    type: "earth",
    attack: "special",
    power: 45,
    accuracy: 100,
  },
  "Wind Shuriken": {
    name: "Wind Shuriken",
    desc_pt: "Uma versão arremessável da técnica Wind Palm com 20% de chance de reduzir a [001]DEF em [-1][000] do Oponente.",
    desc_en: "A throwable version of the Wind Palm technique with a 20% chance to lower [001]DEF[-1][000] of the opponent.",
    type: "wind",
    attack: "physical",
    power: 70,
    accuracy: 100,
  },
  "Wind Palm": {
    name: "Wind Palm",
    type: "wind",
    attack: "physical",
    power: 60,
    accuracy: 80,
  },
  "Smoke Screen": {
    name: "Smoke Screen",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Clone Barrage": {
    name: "Clone Barrage",
    type: "neutral",
    attack: "physical",
    power: 45,
    accuracy: 100,
  },
  "Aerial Combo": {
    name: "Aerial Combo",
    type: "neutral",
    attack: "physical",
    power: 45,
    accuracy: 100,
  },
  "Plunder": {
    name: "Plunder",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Spiritual Pressure": {
    name: "Spiritual Pressure",
    type: "soul",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Sword Slash": {
    name: "Sword Slash",
    type: "neutral",
    attack: "physical",
    power: 30,
    accuracy: 100,
  },
  "Blade Surge": {
    name: "Blade Surge",
    type: "neutral",
    attack: "physical",
    power: 40,
    accuracy: 100,
  },
  "Sword Slam": {
    name: "Sword Slam",
    type: "neutral",
    attack: "physical",
    power: 40,
    accuracy: 100,
  },
  "Lunge": {
    name: "Lunge",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 0,
  },
  "Moon Fang Slash": {
    name: "Moon Fang Slash",
    type: "dark",
    attack: "special",
    power: 65,
    accuracy: 100,
  },
  "Moon Fang Barrage": {
    name: "Moon Fang Barrage",
    desc_pt: "Golpes rápidos com lâminas de chamas negras. A chance de acerto crítico [001]aumenta em 2x[000] a cada turno em que for usado consecutivamente.",
    desc_en: "Rapidly slash with blades of black flame. Critical chance is [001]increased by 2x[000] each turn it is used consecutively.",
    type: "dark",
    attack: "special",
    power: 55,
    accuracy: 100,
  },
  "Menacing Aura": {
    name: "Menacing Aura",
    type: "dark",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Cut Down": {
    name: "Cut Down",
    type: "dark",
    attack: "physical",
    power: 40,
    accuracy: 100,
  },
  "Heavenly Flame": {
    name: "Heavenly Flame",
    type: "fire",
    attack: "status",
    power: 0,
    accuracy: 60,
  },
  "Electric Strike Spear": {
    name: "Rubber Balloon",
    type: "lightning",
    attack: "special",
    power: 0,
    accuracy: 0,
  },
  "Pheonix Fire Bomb": {
    name: "Pheonix Fire Bomb",
    type: "fire",
    attack: "physical",
    power: 70,
    accuracy: 100,
  },
  "Vengeful Illusion": {
    name: "Vengeful Illusion",
    type: "dark",
    attack: "status",
    power: 0,
    accuracy: 70,
  },
  "Electric Strike": {
    name: "Electric Strike",
    type: "lightning",
    attack: "physical",
    power: 60,
    accuracy: 75,
  },
  "Tiger's Barrage": {
    name: "Tiger's Barrage",
    type: "neutral",
    attack: "physical",
    power: 45,
    accuracy: 100,
  },
  "Fireball": {
    name: "Fireball",
    type: "fire",
    attack: "special",
    power: 50,
    accuracy: 100,
  },
  "Kunai Barrage": {
    name: "Kunai Barrage",
    type: "neutral",
    attack: "physical",
    power: 45,
    accuracy: 100,
  },
  "Drain Life": {
    name: "Drain Life",
    type: "psychic",
    attack: "physical",
    power: 60,
    accuracy: 80,
  },
  "Vanishing Blow": {
    name: "Vanishing Blow",
    type: "neutral",
    attack: "physical",
    power: 45,
    accuracy: 100,
  },
  "Solar Flare": {
    name: "Solar Flare",
    type: "light",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Demon Elbow": {
    name: "Demon Elbow",
    type: "demon",
    attack: "physical",
    power: 70,
    accuracy: 0,
  },
  "Limb Regrowth": {
    name: "Limb Regrowth",
    type: "nature",
    attack: "status",
    power: 0,
    accuracy: 0,
  },
  "Angry Explosion": {
    name: "Angry Explosion",
    type: "psychic",
    attack: "special",
    power: 50,
    accuracy: 100,
  },
  "Rest": {
    name: "Rest",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 0,
  },
  "Candy Beam": {
    name: "Candy Beam",
    type: "psychic",
    attack: "status",
    power: 0,
    accuracy: 80,
  },
  "Psychic Blast": {
    name: "Psychic Blast",
    type: "psychic",
    attack: "special",
    power: 40,
    accuracy: 100,
  },
  "Energy Charge": {
    name: "Energy Charge",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 0,
  },
  "Rubber Balloon": {
    name: "Rubber Balloon",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Punch": {
    name: "Punch",
    type: "neutral",
    attack: "physical",
    power: 35,
    accuracy: 100,
  },
  "Rapid Punches": {
    name: "Rapid Punches",
    type: "neutral",
    attack: "physical",
    power: 35,
    accuracy: 100,
  },
  "Rubber Pistol": {
    name: "Rubber Pistol",
    type: "fighting",
    attack: "physical",
    power: 35,
    accuracy: 100,
  },
  "Fighting Spirit": {
    name: "Fighting Spirit",
    type: "fighting",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Bazooka": {
    name: "Bazooka",
    desc_pt: "Arremesse seu oponente para longe com força, usando as duas palmas das mãos.",
    desc_en: "Blast your opponent away on impact with two forceful palms.",
    type: "fighting",
    attack: "physical",
    power: 65,
    accuracy: 90,
  },
  "Phase Two": {
    name: "Phase Two",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Headbutt": {
    name: "Headbutt",
    type: "neutral",
    attack: "physical",
    power: 40,
    accuracy: 80,
  },
  "Armament": {
    name: "Armament",
    type: "fighting",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Energy Blast": {
    name: "Energy Blast",
    type: "neutral",
    attack: "special",
    power: 25,
    accuracy: 100,
  }
};