const moves = {
  "Dexterity": {
    name: "Dexterity",
    desc_pt: "Exiba sua proficiência com suas armas, aumentando sua [002]ACCURACY [+2][000].",
    desc_en: "Flaunt your proficiency with your weapons, increasing your [002]ACCURACY [+2][000].",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Slashgiri": {
    name: "Slashgiri",
    desc_pt: "Reúna suas lâminas para atacar seu oponente num instante, com baixa chance de [005]ferir[000] ao acertar.",
    desc_en: "Gather your blades to strike your opponent in a flash, low chance to inflict [005]wounded[000] on hit.",
    type: "wind",
    attack: "physical",
    power: 65,
    accuracy: 100,
  },
  "108 Hawk": {
    name: "108 Hawk",
    desc_pt: "Um golpe voador em espiral. Causa dano baseado na DEF em vez da SP.DEF.",
    desc_en: "A spiraling flying slash. Deals damage based on DEF instead of SP.DEF.",
    type: "wind",
    attack: "special",
    power: 70,
    accuracy: 100,
  },
  "5000 Worlds": {
    name: "5000 Worlds",
    desc_pt: "Gire suas lâminas em preparação, depois ataque seu oponente com um golpe mortal.",
    desc_en: "Spin your blades in preparation, then cut your opponent with a deadly attack.",
    type: "wind",
    attack: "physical",
    power: 90,
    accuracy: 80,
  },
  "Sinister Presence": {
    name: "Sinister Presence",
    desc_pt: "Uma sensação de pavor toma conta do seu oponente enquanto você está diante dele, fazendo-o temer seus ataques. Diminui a [001]DEF [-1][000] do Oponente.",
    desc_en: "A feeling of dread falls on your opponent as you stand in front of them making them scared of yours attacks. Decreases the opponent's [001]DEF [-1][000].",
    type: "demon",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Tiger Song": {
    name: "Tiger Song",
    type: "wind",
    attack: "physical",
    accuracy: 100,
  },
  "Junk Toss": {
    name: "Junk Toss",
    desc_pt: "Arremesse objetos inúteis em um alvo, com a potência dependendo do item arremessado.",
    desc_en: "Throw junk at a target with the power depending on the item thrown.",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Taunt": {
    name: "Taunt",
    desc_pt: "Provoque o inimigo! Impede-o de usar golpes de status e o obriga a atacá-lo de frente!",
    desc_en: "Taunt the enemy! Stopping them from using status moves and having to attack you head on!",
    type: "dark",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Rifle Shot": {
    name: "Rifle Shot",
    desc_pt: "Dispare seu rifle.",
    desc_en: "Shoot off your rifle.",
    type: "neutral",
    attack: "special",
    power: 40,
    accuracy: 100,
  },
  "Missile Barrage": {
    name: "Missile Barrage",
    desc_pt: "Dispare mísseis de um RPG contra um alvo com 20% de chance de [003]queimá-lo[000].",
    desc_en: "Shoot missiles from a RPG at a target with 20% chance to [003]burn them[000].",
    type: "neutral",
    attack: "special",
    power: 50,
    accuracy: 100,
  },
  "Thunder Set": {
    name: "Thunder Set",
    desc_pt: "Aumenta o [002]SP.ATK [+2][000] ao carregar com energia elétrica.",
    desc_en: "Raise [002]SP.ATK [+2][000] by charging with electric energy.",
    type: "lightning",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Electric Horn Angle": {
    name: "Electric Horn Angle",
    desc_pt: "Uma corneta elétrica que causa o [002]dobro do dano base[000] se você tiver Sp.Atk [+3].",
    desc_en: "An electric horn that does [002]double the base damage[000] if you have Sp.Atk [+3].",
    type: "lightning",
    attack: "physical",
    power: 60,
    accuracy: 100,
  },
  "Discharge": {
    name: "Discharge",
    desc_pt: "Envie raios através do solo para [008]paralisar[000] múltiplos alvos.",
    desc_en: "Send lightning through the ground to [008]paralyze[000] multiple targets.",
    type: "lightning",
    attack: "status",
    power: 0,
    accuracy: 55,
  },
  "Lightning Strike": {
    name: "Lightning Strike",
    desc_pt: "Um relâmpago com 20% de chance de [008]paralisar[000] o alvo.",
    desc_en: "A crash of lightning with a 20% chance to [008]paralyze[000] the target.",
    type: "lightning",
    attack: "special",
    power: 60.5,
    accuracy: 75,
  },
  "Precise Energy Beam": {
    name: "Precise Energy Beam",
    desc_pt: "Concentre intensamente sua energia na ponta dos dedos, carregando-a por 2 turnos. Em seguida, libere essa energia formando uma poderosa broca.",
    desc_en: "Concentrate your energy intensely at your fingertips, charging it for 2 turns. Then release this energy forming a powerful drill.",
    type: "psychic",
    attack: "special",
    power: 150,
    accuracy: 100,
  },
  "Energy Shell": {
    name: "Energy Shell",
    desc_pt: "Uma barreira que impede o próximo ataque. Ataques Especiais serão anulados, habilidades Físicas causarão metade do dano e o alvo ficará [008]paralisado[000].",
    desc_en: "A barrier that stops the next attack. Special attacks will be negated, physical skills will do halve damage and be [008]paralyzed[000].",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Galaxy Cannon": {
    name: "Galaxy Cannon",
    type: "fighting",
    attack: "special",
    power: 75,
    accuracy: 100,
  },
  "Galaxy Burst": {
    name: "Galaxy Burst",
    type: "fighting",
    attack: "physical",
    power: 70,
    accuracy: 100,
  },
  "Energy Beam": {
    name: "Energy Beam",
    type: "neutral",
    attack: "special",
    power: 60,
    accuracy: 100,
  },
  "Dirty Fireworks": {
    name: "Dirty Fireworks",
    type: "fighting",
    attack: "physical",
    power: 55,
    accuracy: 100,
  },
  "Divine Bomb": {
    name: "Divine Bomb",
    type: "light",
    attack: "special",
    power: 250,
    accuracy: 100,
  },
  "Meteor Combo": {
    name: "Meteor Combo",
    type: "fighting",
    attack: "physical",
    power: 75,
    accuracy: 100,
  },
  "Super Energy Wave": {
    name: "Super Energy Wave",
    type: "fighting",
    attack: "special",
    power: 60,
    accuracy: 100,
  },
  "Cyclone Throw": {
    name: "Cyclone Throw",
    type: "fighting",
    attack: "physical",
    power: 50,
    accuracy: 100,
  },
  "Energy Wave": {
    name: "Energy Wave",
    type: "fighting",
    attack: "special",
    power: 40,
    accuracy: 100,
  },
  "Guzzle": {
    name: "Guzzle",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Reverse Lily": {
    name: "Reverse Lily",
    type: "fighting",
    attack: "physical",
    power: 100,
    accuracy: 100,
  },
  "Dive Kick": {
    name: "Dive Kick",
    type: "fighting",
    attack: "physical",
    power: 50,
    accuracy: 85,
  },
  "Afterimage": {
    name: "Afterimage",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 0,
  },
  "Sand Arm": {
    name: "Sand Arm",
    type: "demon",
    attack: "physical",
    power: 70,
    accuracy: 100,
  },
  "Substitution": {
    name: "Substitution",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Sand Bomb": {
    name: "Sand Bomb",
    type: "earth",
    attack: "special",
    power: 65,
    accuracy: 100,
  },
  "Sand Burial": {
    name: "Sand Burial",
    type: "earth",
    attack: "special",
    power: 60,
    accuracy: 70,
  },
  "Sand Storm": {
    name: "Sand Storm",
    type: "earth",
    attack: "special",
    power: 0,
    accuracy: 100,
  },
  "Sand Tsunami": {
    name: "Sand Tsunami",
    type: "earth",
    attack: "special",
    power: 45,
    accuracy: 100,
  },
  "Wind Shuriken": {
    name: "Wind Shuriken",
    desc_pt: "Uma versão arremessável da técnica Wind Palm com 20% de chance de reduzir a [001]DEF em [-1][000] do Oponente.",
    desc_en: "A throwable version of the Wind Palm technique with a 20% chance to lower [001]DEF[-1][000] of the opponent.",
    type: "wind",
    attack: "physical",
    power: 70,
    accuracy: 100,
  },
  "Wind Palm": {
    name: "Wind Palm",
    type: "wind",
    attack: "physical",
    power: 60,
    accuracy: 80,
  },
  "Smoke Screen": {
    name: "Smoke Screen",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Clone Barrage": {
    name: "Clone Barrage",
    type: "neutral",
    attack: "physical",
    power: 45,
    accuracy: 100,
  },
  "Aerial Combo": {
    name: "Aerial Combo",
    type: "neutral",
    attack: "physical",
    power: 45,
    accuracy: 100,
  },
  "Plunder": {
    name: "Plunder",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Spiritual Pressure": {
    name: "Spiritual Pressure",
    type: "soul",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Sword Slash": {
    name: "Sword Slash",
    type: "neutral",
    attack: "physical",
    power: 30,
    accuracy: 100,
  },
  "Blade Surge": {
    name: "Blade Surge",
    type: "neutral",
    attack: "physical",
    power: 40,
    accuracy: 100,
  },
  "Sword Slam": {
    name: "Sword Slam",
    type: "neutral",
    attack: "physical",
    power: 40,
    accuracy: 100,
  },
  "Lunge": {
    name: "Lunge",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 0,
  },
  "Moon Fang Slash": {
    name: "Moon Fang Slash",
    desc_pt: "Libere uma poderosa onda de energia espiritual de sua espada.",
    desc_en: "Unleash a powerful spiritual energy wave from your sword.",
    type: "dark",
    attack: "special",
    power: 65,
    accuracy: 100,
  },
  "Moon Fang Barrage": {
    name: "Moon Fang Barrage",
    desc_pt: "Golpes rápidos com lâminas de chamas negras. A chance de acerto crítico [002]aumenta em 2x[000] a cada turno em que for usado consecutivamente.",
    desc_en: "Rapidly slash with blades of black flame. Critical chance is [002]increased by 2x[000] each turn it is used consecutively.",
    type: "dark",
    attack: "special",
    power: 55,
    accuracy: 100,
  },
  "Menacing Aura": {
    name: "Menacing Aura",
    type: "dark",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Cut Down": {
    name: "Cut Down",
    type: "dark",
    attack: "physical",
    power: 40,
    accuracy: 100,
  },
  "Heavenly Flame": {
    name: "Heavenly Flame",
    type: "fire",
    attack: "status",
    power: 0,
    accuracy: 60,
  },
  "Electric Strike Spear": {
    name: "Rubber Balloon",
    type: "lightning",
    attack: "special",
    power: 0,
    accuracy: 0,
  },
  "Pheonix Fire Bomb": {
    name: "Pheonix Fire Bomb",
    type: "fire",
    attack: "physical",
    power: 70,
    accuracy: 100,
  },
  "Vengeful Illusion": {
    name: "Vengeful Illusion",
    type: "dark",
    attack: "status",
    power: 0,
    accuracy: 70,
  },
  "Electric Strike": {
    name: "Electric Strike",
    type: "lightning",
    attack: "physical",
    power: 60,
    accuracy: 75,
  },
  "Tiger's Barrage": {
    name: "Tiger's Barrage",
    type: "neutral",
    attack: "physical",
    power: 45,
    accuracy: 100,
  },
  "Fireball": {
    name: "Fireball",
    type: "fire",
    attack: "special",
    power: 50,
    accuracy: 100,
  },
  "Kunai Barrage": {
    name: "Kunai Barrage",
    type: "neutral",
    attack: "physical",
    power: 45,
    accuracy: 100,
  },
  "Drain Life": {
    name: "Drain Life",
    type: "psychic",
    attack: "physical",
    power: 60,
    accuracy: 80,
  },
  "Vanishing Blow": {
    name: "Vanishing Blow",
    type: "neutral",
    attack: "physical",
    power: 45,
    accuracy: 100,
  },
  "Solar Flare": {
    name: "Solar Flare",
    type: "light",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Demon Elbow": {
    name: "Demon Elbow",
    type: "demon",
    attack: "physical",
    power: 70,
    accuracy: 0,
  },
  "Limb Regrowth": {
    name: "Limb Regrowth",
    type: "nature",
    attack: "status",
    power: 0,
    accuracy: 0,
  },
  "Angry Explosion": {
    name: "Angry Explosion",
    type: "psychic",
    attack: "special",
    power: 50,
    accuracy: 100,
  },
  "Rest": {
    name: "Rest",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 0,
  },
  "Candy Beam": {
    name: "Candy Beam",
    type: "psychic",
    attack: "status",
    power: 0,
    accuracy: 80,
  },
  "Psychic Blast": {
    name: "Psychic Blast",
    type: "psychic",
    attack: "special",
    power: 40,
    accuracy: 100,
  },
  "Energy Charge": {
    name: "Energy Charge",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 0,
  },
  "Rubber Balloon": {
    name: "Rubber Balloon",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Punch": {
    name: "Punch",
    type: "neutral",
    attack: "physical",
    power: 35,
    accuracy: 100,
  },
  "Rapid Punches": {
    name: "Rapid Punches",
    type: "neutral",
    attack: "physical",
    power: 35,
    accuracy: 100,
  },
  "Rubber Pistol": {
    name: "Rubber Pistol",
    type: "fighting",
    attack: "physical",
    power: 35,
    accuracy: 100,
  },
  "Fighting Spirit": {
    name: "Fighting Spirit",
    type: "fighting",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Bazooka": {
    name: "Bazooka",
    desc_pt: "Arremesse seu oponente para longe com força, usando as duas palmas das mãos.",
    desc_en: "Blast your opponent away on impact with two forceful palms.",
    type: "fighting",
    attack: "physical",
    power: 65,
    accuracy: 90,
  },
  "Phase Two": {
    name: "Phase Two",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Headbutt": {
    name: "Headbutt",
    type: "neutral",
    attack: "physical",
    power: 40,
    accuracy: 80,
  },
  "Armament": {
    name: "Armament",
    desc_pt: "Vista-se com uma armadura preta para aumentar seu [002]ATK [+1][000] e permitir que você acerte inimigos intangíveis.",
    desc_en: "Coat yourself in a armor black to increase your [002]ATK [+1][000] and allow you to hit intangible enemies.",
    type: "fighting",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Energy Blast": {
    name: "Energy Blast",
    type: "neutral",
    attack: "special",
    power: 25,
    accuracy: 100,
  }
};