const moves = {
  "Lightning Spread": {
    name: "Lightning Spread",
    desc_pt: "Libera um choque elétrico que ignora precisão e esquiva.",
    desc_en: "Release an electric shock that ignores accuracy and evasion.",
    type: "lightning",
    attack: "special",
    power: 65,
    accuracy: 100,
    pp: 15,
  },
  "False Courage": {
    name: "False Courage",
    desc_pt: "Reúna sua determinação para não ser afetado por [007]dormência[000], [008]paralisia[000] ou recuar por 3 turnos.",
    desc_en: "Gather your resolve to not be affected by [007]sleep[000], [008]paralyze[000], or flinch for 3 turns.",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Shark Tile Fist": {
    name: "Shark Tile Fist",
    type: "water",
    attack: "physical",
    accuracy: 100,
  },
  "Brick Fist": {
    name: "Brick Fist",
    desc_pt: "Um soco pesado e reto que ignora qualquer aumento no atributo DEF do alvo.",
    desc_en: "A heavy straight fist that ignores any increases to a target DEF stat.",
    type: "fighting",
    attack: "physical",
    power: 60,
    accuracy: 100,
  },
  "Shark Throw": {
    name: "Shark Throw",
    desc_pt: "Arremesse um alvo de um redemoinho. Isso diminui a prioridade dele e o força a recuar.",
    desc_en: "Throw a target from a whirlpool. This has decreased priority and forces them to retreat.",
    type: "water",
    attack: "special",
    power: 30,
    accuracy: 100,
  },
  "Water Spear": {
    name: "Water Spear",
    desc_pt: "Flechas de água capazes de perfurar múltiplos inimigos, com uma chance de acerto crítico 4 vezes maior.",
    desc_en: "Arrows of water that can pierce multiple enemies, having a increased 4X critical chance.",
    type: "water",
    attack: "special",
    power: 50,
    accuracy: 100,
  },
  "Sharp Claw": {
    name: "Sharp Claw",
    desc_pt: "Arranhe seu oponente com garras afiadas.",
    desc_en: "Scratch at your opponent with sharp claws.",
    type: "beast",
    attack: "physical",
    power: 35,
    accuracy: 100,
  },
  "Coated Blade": {
    name: "Coated Blade",
    desc_pt: "Lâmina que secreta um veneno letal com 30% de chance de [006]envenenar[000] por 5 turnos. [006]Envenena[000] instantaneamente se o alvo estiver [005]ferido[000].",
    desc_en: "Blade secreting a lethal poison with a 30% chance to [006]poison[000] for 5 turns. Instantly [006]poisons[000] if target is [005]wounded[000].",
    type: "poison",
    attack: "physical",
    power: 60,
    accuracy: 100,
  },
  "Desert Espada": {
    name: "Desert Espada",
    desc_pt: "Uma lâmina de areia que irrompe do chão abaixo de você com 30% de chance de reduzir a [001]DEF [-1][000] do inimigo.",
    desc_en: "A blade of sand that erupts from the ground beneath you with a 30% chance to lower enemy [001]SPDEF [-1][000].",
    type: "earth",
    attack: "special",
    power: 60,
    accuracy: 100,
  },
  "Crush": {
    name: "Crush",
    desc_pt: "Esmague um alvo sob seus pés e cause mais dano com base na diferença entre sua saúde máxima e a dele.",
    desc_en: "Crush a target under you, deal more damage based on the difference between your max health.",
    type: "neutral",
    attack: "physical",
    power: 30,
    accuracy: 100,
  },
  "Fury": {
    name: "Fury",
    desc_pt: "Fique com raiva, aumentando seu [002]ATK [+2][000], mas você fica mais distraído, perdendo [001]DEF [-1][000] e [001]Evasão [-1][000].",
    desc_en: "Become angry, raising your ATK [+2] but you become more distracted losing [001]DEF [-1][000] and [001]Evasive [-1][000].",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Z Bomb": {
    name: "Z Bomb",
    desc_pt: "Uma bomba gigante de ki que destrói o campo ao impacto, reduz seu [001]SP.ATK [-3][000] após usá-la.",
    desc_en: "A giant bomb of ki that destroys the field on impact, decrease your [001]SP.ATK [-3][000] after using it.",
    type: "dark",
    attack: "special",
    power: 140,
    accuracy: 100,
  },
  "Jet Bullet": {
    name: "Jet Bullet",
    desc_pt: "Uma versão quase instantânea da habilidade Bazooka, com velocidade equivalente ao seu alcance.",
    desc_en: "An almost instant version of the Bazooka ability with a speed to match its reach.",
    type: "fighting",
    attack: "physical",
    power: 60,
    accuracy: 100,
  },
  "Red Talon": {
    name: "Red Talon",
    type: "fire",
    attack: "physical",
    power: 65,
    accuracy: 100,
  },
  "Mystic Shot": {
    name: "Mystic Shot",
    desc_pt: "Um dardo de energia mística com 10% de chance de reduzir a [001]SP.DEF [-1][000] do alvo.",
    desc_en: "A dart of mystical energy with a 10% chance to lower target [001]SP.DEF [-1][000].",
    type: "psychic",
    attack: "special",
    power: 40,
    accuracy: 100,
  },
  "Explosion": {
    name: "Explosion",
    desc_pt: "Recite um encantamento por 2 turnos, libere uma explosão de magia arcana que atinja múltiplos alvos. Em seguida, fique incapacitado por 2 turnos.",
    desc_en: "Chant an incantation for 2 turns, let forth an arch magic explosion to hit multiple targets. Then, get disabled for 2 turns.",
    type: "fire",
    attack: "special",
    power: 300,
    accuracy: 100,
  },
  "Charm": {
    name: "Charm",
    desc_pt: "Atraia um alvo com seu olhar, fazendo com que ele erre seus ataques por 3 turnos.",
    desc_en: "Attract a target with your looks, making them miss when they try to hit you for 3 turns.",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 60,
    pp: 8,
  },
  "Fire Zone": {
    name: "Fire Zone",
    desc_pt: "Crie uma zona de fogo que fortaleça os movimentos do tipo fogo em [002]1,3x[000] por 3 turnos.",
    desc_en: "Create a zone of fire that empowers fire type moves [002]1.3x[000] for 3 turns.",
    type: "fire",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Fortune": {
    name: "Fortune",
    desc_pt: "Uma boa sorte aumenta sua [002]SP.DEF [+1][000] e [002]Evasão [+1][000].",
    desc_en: "A good fortune increases your [002]SP.DEF [+1][000] and [002]Evasive [+1][000].",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Wide Explosion": {
    name: "Wide Explosion",
    desc_pt: "Uma explosão que se espalha pelo campo, atingindo múltiplos alvos e com 20% de chance de causar [003]queimadura[000].",
    desc_en: "An explosion across the field that hits multiple targets and has a 20% chance to [003]burn[000].",
    type: "fire",
    attack: "special",
    power: 40,
    accuracy: 100,
  },
  "Lightning Spear": {
    name: "Lightning Spear",
    desc_pt: "Uma lança crepitante feita para longo alcance com 10% de chance de reduzir a [001]SP.DEF [-1][000] do alvo e [008]paralisá-lo[000].",
    desc_en: "A crackling spear meant for long range with a 10% chance to lower target [001]SPDEF[-1][000] and [008]paralyze[000] them.",
    type: "lightning",
    attack: "special",
    power: 60,
    accuracy: 100,
  },
  "Dexterity": {
    name: "Dexterity",
    desc_pt: "Exiba sua proficiência com suas armas, aumentando sua [002]ACCURACY [+2][000].",
    desc_en: "Flaunt your proficiency with your weapons, increasing your [002]ACCURACY [+2][000].",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Slashgiri": {
    name: "Slashgiri",
    desc_pt: "Reúna suas lâminas para atacar seu oponente num instante, com baixa chance de [005]ferir[000] ao acertar.",
    desc_en: "Gather your blades to strike your opponent in a flash, low chance to inflict [005]wounded[000] on hit.",
    type: "wind",
    attack: "physical",
    power: 65,
    accuracy: 100,
  },
  "108 Hawk": {
    name: "108 Hawk",
    desc_pt: "Um golpe voador em espiral. Causa dano baseado na DEF em vez da SP.DEF.",
    desc_en: "A spiraling flying slash. Deals damage based on DEF instead of SP.DEF.",
    type: "wind",
    attack: "special",
    power: 70,
    accuracy: 100,
  },
  "5000 Worlds": {
    name: "5000 Worlds",
    desc_pt: "Gire suas lâminas em preparação, depois ataque seu oponente com um golpe mortal.",
    desc_en: "Spin your blades in preparation, then cut your opponent with a deadly attack.",
    type: "wind",
    attack: "physical",
    power: 90,
    accuracy: 80,
  },
  "Sinister Presence": {
    name: "Sinister Presence",
    desc_pt: "Uma sensação de pavor toma conta do seu oponente enquanto você está diante dele, fazendo-o temer seus ataques. Diminui a [001]DEF [-1][000] do Oponente.",
    desc_en: "A feeling of dread falls on your opponent as you stand in front of them making them scared of yours attacks. Decreases the opponent's [001]DEF [-1][000].",
    type: "demon",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Tiger Song": {
    name: "Tiger Song",
    type: "wind",
    attack: "physical",
    accuracy: 100,
  },
  "Junk Toss": {
    name: "Junk Toss",
    desc_pt: "Arremesse objetos inúteis em um alvo, com a potência dependendo do item arremessado.",
    desc_en: "Throw junk at a target with the power depending on the item thrown.",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Taunt": {
    name: "Taunt",
    desc_pt: "Provoque o inimigo! Impede-o de usar golpes de status e o obriga a atacá-lo de frente!",
    desc_en: "Taunt the enemy! Stopping them from using status moves and having to attack you head on!",
    type: "dark",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Rifle Shot": {
    name: "Rifle Shot",
    desc_pt: "Dispare seu rifle.",
    desc_en: "Shoot off your rifle.",
    type: "neutral",
    attack: "special",
    power: 40,
    accuracy: 100,
  },
  "Missile Barrage": {
    name: "Missile Barrage",
    desc_pt: "Dispare mísseis de um RPG contra um alvo com 20% de chance de [003]queimá-lo[000].",
    desc_en: "Shoot missiles from a RPG at a target with 20% chance to [003]burn[000] them.",
    type: "neutral",
    attack: "special",
    power: 50,
    accuracy: 100,
  },
  "Thunder Set": {
    name: "Thunder Set",
    desc_pt: "Carregue com energia elétrica com 50% de chance de aumentar [002]SP.ATK [+1][000] ou [002][+2][000].",
    desc_en: "Charge with electrical energy with a 50% chance to raise [002]SP.ATK [+1][000] or [002][+2][000].",
    type: "lightning",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Electric Horn Angle": {
    name: "Electric Horn Angle",
    desc_pt: "Uma corneta elétrica que causa o [002]dobro do dano base[000] se você tiver Sp.Atk [+3].",
    desc_en: "An electric horn that does [002]double the base damage[000] if you have Sp.Atk [+3].",
    type: "lightning",
    attack: "physical",
    power: 60,
    accuracy: 100,
  },
  "Discharge": {
    name: "Discharge",
    desc_pt: "Envie raios através do solo para [008]paralisar[000] múltiplos alvos.",
    desc_en: "Send lightning through the ground to [008]paralyze[000] multiple targets.",
    type: "lightning",
    attack: "status",
    power: 0,
    accuracy: 55,
    pp: 10,
  },
  "Lightning Strike": {
    name: "Lightning Strike",
    desc_pt: "Um relâmpago com 20% de chance de [008]paralisar[000] o alvo.",
    desc_en: "A crash of lightning with a 20% chance to [008]paralyze[000] the target.",
    type: "lightning",
    attack: "special",
    power: 60.5,
    accuracy: 75,
  },
  "Precise Energy Beam": {
    name: "Precise Energy Beam",
    desc_pt: "Concentre intensamente sua energia na ponta dos dedos, carregando-a por 2 turnos. Em seguida, libere essa energia formando uma poderosa broca.",
    desc_en: "Concentrate your energy intensely at your fingertips, charging it for 2 turns. Then release this energy forming a powerful drill.",
    type: "psychic",
    attack: "special",
    power: 150,
    accuracy: 100,
  },
  "Energy Shell": {
    name: "Energy Shell",
    desc_pt: "Uma barreira que impede o próximo ataque. Ataques Especiais serão anulados, habilidades Físicas causarão metade do dano e o alvo ficará [008]paralisado[000].",
    desc_en: "A barrier that stops the next attack. Special attacks will be negated, physical skills will do halve damage and be [008]paralyzed[000].",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Galaxy Cannon": {
    name: "Galaxy Cannon",
    type: "fighting",
    attack: "special",
    power: 75,
    accuracy: 100,
  },
  "Galaxy Burst": {
    name: "Galaxy Burst",
    type: "fighting",
    attack: "physical",
    power: 70,
    accuracy: 100,
  },
  "Energy Beam": {
    name: "Energy Beam",
    type: "neutral",
    attack: "special",
    power: 60,
    accuracy: 100,
  },
  "Dirty Fireworks": {
    name: "Dirty Fireworks",
    type: "fighting",
    attack: "physical",
    power: 55,
    accuracy: 100,
  },
  "Divine Bomb": {
    name: "Divine Bomb",
    type: "light",
    attack: "special",
    power: 250,
    accuracy: 100,
  },
  "Meteor Combo": {
    name: "Meteor Combo",
    type: "fighting",
    attack: "physical",
    power: 75,
    accuracy: 100,
  },
  "Super Energy Wave": {
    name: "Super Energy Wave",
    type: "fighting",
    attack: "special",
    power: 60,
    accuracy: 100,
  },
  "Cyclone Throw": {
    name: "Cyclone Throw",
    desc_pt: "Gire o alvo antes de arremessá-lo. Isso diminui a prioridade e o força a recuar.",
    desc_en: "Spin a target around before tossing them. This has decreased priority and forces them to retreat.",
    type: "fighting",
    attack: "physical",
    power: 30,
    accuracy: 100,
  },
  "Energy Wave": {
    name: "Energy Wave",
    type: "fighting",
    attack: "special",
    power: 40,
    accuracy: 100,
  },
  "Guzzle": {
    name: "Guzzle",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Reverse Lily": {
    name: "Reverse Lily",
    type: "fighting",
    attack: "physical",
    power: 100,
    accuracy: 100,
  },
  "Dive Kick": {
    name: "Dive Kick",
    type: "fighting",
    attack: "physical",
    power: 50,
    accuracy: 85,
  },
  "Afterimage": {
    name: "Afterimage",
    desc_pt: "Movimente-se rapidamente e produza uma pós-imagem, aumenta o [002]SPD [+2][000].",
    desc_en: "Move fast and produce  an afterimage, increases [002]SPD [+2][000].",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 0,
  },
  "Sand Arm": {
    name: "Sand Arm",
    desc_pt: "Um braço de areia demoníaco com 20% de chance de diminuir a [001]SPD [-1][000].",
    desc_en: "A demonic sand arm with 20% chance to lower [001]SPD [-1][000].",
    type: "demon",
    attack: "physical",
    power: 70,
    accuracy: 100,
  },
  "Substitution": {
    name: "Substitution",
    desc_pt: "Troque por um substituto, gaste 20% de HP e o próximo ataque que te atingir errará. Se você não tiver HP suficiente, este movimento falhará.",
    desc_en: "Swap out for a substitute, spend 20% HP and the next attack to hit you will miss. If you don't have enough HP this move will fail.",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Sand Bomb": {
    name: "Sand Bomb",
    desc_pt: "Colete areia para esmagar seu alvo com prioridade reduzida; isso o atingirá ignorando o Accuracy ou a evasão.",
    desc_en: "Collect sand to crush your target with decreased priority, this will hit ignoring accuracy, or evasive.",
    type: "earth",
    attack: "special",
    power: 65,
    accuracy: 100,
  },
  "Sand Burial": {
    name: "Sand Burial",
    desc_pt: "Esmague o oponente em um caixão de areia que incapacita o alvo por 2 turnos. Falha se o alvo já estiver incapacitado.",
    desc_en: "Crush the opponent in a coffin made of sand that disables the target for 2 turns. Fails if target is already disabled.",
    type: "earth",
    attack: "special",
    power: 60,
    accuracy: 70,
  },
  "Sand Storm": {
    name: "Sand Storm",
    desc_pt: "Invoca uma tempestade de areia que causa dano equivalente a 1/12 do HP desde que não sejam do tipo Terra por 5 turnos.",
    desc_en: "Summon a sandstorm that deals 1/12th HP damage to non-Earth types for 5 turns.",
    type: "earth",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Sand Tsunami": {
    name: "Sand Tsunami",
    desc_pt: "Uma onda de areia que atinge inimigos adjacentes, com 80% de chance de reduzir sua [001]SPD [-1][000].",
    desc_en: "A wave of sand thats hits adjacent enemies, and an 80% chance to lower their [001]SPD [-1][000].",
    type: "earth",
    attack: "special",
    power: 45,
    accuracy: 100,
  },
  "Wind Shuriken": {
    name: "Wind Shuriken",
    desc_pt: "Uma versão arremessável da técnica Wind Palm com 20% de chance de reduzir a [001]DEF [-1][000] do Oponente.",
    desc_en: "A throwable version of the Wind Palm technique with a 20% chance to lower [001]DEF[-1][000] of the opponent.",
    type: "wind",
    attack: "physical",
    power: 70,
    accuracy: 100,
  },
  "Wind Palm": {
    name: "Wind Palm",
    desc_pt: "O usuário carrega uma bola espiral de energia eólica e a empurra contra o oponente, fazendo-o girar no ar.[004](Tem chance de dar Confusão no oponente)[000]",
    desc_en: "The user charges a spiral ball of wind energy and shoves it into the opponent sending them spinning in the air.[004](There's a chance it will confuse the opponent)[000]",
    type: "wind",
    attack: "physical",
    power: 60,
    accuracy: 80,
  },
  "Smoke Screen": {
    name: "Smoke Screen",
    desc_pt: "Lance uma bomba de fumaça, aumente a [002]Evasão [+1][000].",
    desc_en: "Throw a smokebomb, increase [002]Evasion [+1][000].",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Clone Barrage": {
    name: "Clone Barrage",
    desc_pt: "Atacar um alvo com um grupo de clones.",
    desc_en: "Assault a target with a gang of duplicates.",
    type: "neutral",
    attack: "physical",
    power: 65,
    accuracy: 100,
  },
  "Aerial Combo": {
    name: "Aerial Combo",
    desc_pt: "Derrube seu oponente com um ataque aéreo. Causa o dobro de dano se o alvo estiver no ar.",
    desc_en: "Bring your opponent crashing down with an aerial assault. Does double the damage if the target is airborne.",
    type: "neutral",
    attack: "physical",
    power: 45,
    accuracy: 100,
  },
  "Plunder": {
    name: "Plunder",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Spiritual Pressure": {
    name: "Spiritual Pressure",
    desc_pt: "Exerça sua pressão espiritual, diminuindo o [001]SPD [-1][000] de seus inimigos.",
    desc_en: "Exert your spiritual pressure, lowering your enemies [001]SPD [-1][000].",
    type: "soul",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Sword Slash": {
    name: "Sword Slash",
    type: "neutral",
    attack: "physical",
    power: 30,
    accuracy: 100,
  },
  "Blade Surge": {
    name: "Blade Surge",
    type: "neutral",
    attack: "physical",
    power: 40,
    accuracy: 100,
  },
  "Sword Slam": {
    name: "Sword Slam",
    type: "neutral",
    attack: "physical",
    power: 40,
    accuracy: 100,
  },
  "Lunge": {
    name: "Lunge",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 0,
  },
  "Moon Fang Slash": {
    name: "Moon Fang Slash",
    desc_pt: "Libere uma poderosa onda de energia espiritual de sua espada.",
    desc_en: "Unleash a powerful spiritual energy wave from your sword.",
    type: "soul",
    attack: "special",
    power: 65,
    accuracy: 100,
  },
  "Moon Fang Barrage": {
    name: "Moon Fang Barrage",
    desc_pt: "Golpes rápidos com lâminas de chamas negras. A chance de acerto crítico [002]aumenta em 2x[000] a cada turno em que for usado consecutivamente.",
    desc_en: "Rapidly slash with blades of black flame. Critical chance is [002]increased by 2x[000] each turn it is used consecutively.",
    type: "dark",
    attack: "physical",
    power: 55,
    accuracy: 100,
  },
  "Menacing Aura": {
    name: "Menacing Aura",
    desc_pt: "Uma presença ameaçadora que reduz a [001]DEF [-1][000] e a [001]Evasão [-1][000] do alvo.",
    desc_en: "A menacing presence that lowers the target [001]DEF [-1][000] and [001]Evasion [-1][000].",
    type: "dark",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Cut Down": {
    name: "Cut Down",
    desc_pt: "Elimine seu alvo. Se ele estiver recuando, isso terá prioridade e causará o dobro de dano.",
    desc_en: "Cut your target down. If they are retreating, this will take priority and deal 2x damage.",
    type: "dark",
    attack: "physical",
    power: 40,
    accuracy: 100,
  },
  "Heavenly Flame": {
    name: "Heavenly Flame",
    desc_pt: "Lançar uma chama eterna pelos olhos [003]queima[000] o alvo, causando dano equivalente a 1/16 da sua vida.",
    desc_en: "Cast a never-ending flame from your eyes [003]burns[000] a target for 1/16th of their health.",
    type: "fire",
    attack: "status",
    power: 0,
    accuracy: 60,
  },
  "Pheonix Fire Bomb": {
    name: "Phoenix Fire Bomb",
    desc_pt: "Bolas de fogo consecutivas com 20% de chance de [003]queimar[000] o alvo.",
    desc_en: "Consecutive fireballs with a 20% chance to [003]burn[000] a target.",
    type: "fire",
    attack: "physical",
    power: 70,
    accuracy: 100,
  },
  "Vengeful Illusion": {
    name: "Vengeful Illusion",
    desc_pt: "Confunda o alvo com um olhar que distorça sua percepção e seus pensamentos.",
    desc_en: "Confuse the target with a gaze that distorts their perception and thoughts.",
    type: "dark",
    attack: "status",
    power: 0,
    accuracy: 70,
  },
  "Electric Strike": {
    name: "Electric Strike",
    desc_pt: "Ataque um alvo com um raio na palma da sua mão, com 20% de chance de [008]paralisá-lo[000] por 3 turnos.",
    desc_en: "Strike a target with lightning in the palm of yours with a 20% chance to [008]paralyze[000] them for 3 turns",
    type: "lightning",
    attack: "physical",
    power: 60,
    accuracy: 90,
  },
  "Tiger's Barrage": {
    name: "Tiger's Barrage",
    desc_pt: "Uma técnica que envolve uma série rápida e poderosa de chutes e socos, demonstrando a velocidade e precisão excepcionais do usuário.",
    desc_en: "A technique that involves a rapid and powerful series of kicks and punches, showcasing the user's exceptional speed and precision.",
    type: "neutral",
    attack: "physical",
    power: 45,
    accuracy: 100,
  },
  "Fireball": {
    name: "Fireball",
    desc_pt: "Projeta uma bola de fogo no oponente, causando dano e com uma baixa chance[004](20%)[000] de [003]queimá-lo[000].",
    desc_en: "Projects a ball of fire at the opponent dealing damage and having a low change[004](20%)[000] to [003]burn[000] them.",
    type: "fire",
    attack: "special",
    power: 50,
    accuracy: 100,
  },
  "Kunai Barrage": {
    name: "Kunai Barrage",
    desc_pt: "Arremesse várias kunais que atinjam inimigos adjacentes.",
    desc_en: "Throw multiple Kunai that hit adjacent enemies.",
    type: "neutral",
    attack: "physical",
    power: 45,
    accuracy: 100,
  },
  "Drain Life": {
    name: "Drain Life",
    desc_pt: "Roube energia de um alvo agarrando-o, o que [002]cura 60%[000] do dano causado.",
    desc_en: "Steal energy from a target by grabbing them which [002]heals for 60%[000] of the damage dealt.",
    type: "psychic",
    attack: "physical",
    power: 60,
    accuracy: 80,
  },
  "Vanishing Blow": {
    name: "Vanishing Blow",
    desc_pt: "Desapareça e ataque seu oponente com prioridade aumentada.",
    desc_en: "Vanish and strike your opponent with increased priority.",
    type: "fighting",
    attack: "physical",
    power: 35,
    accuracy: 100,
  },
  "Solar Flare": {
    name: "Solar Flare",
    desc_pt: "Uma luz branca ofuscante que reduz a [001]Accuracy [-1][000] e tem 30% de chance de causar hesitação.",
    desc_en: "A blinding white light that lower [001]Accuracy [-1][000] and has a 30% chance to flinch. ",
    type: "light",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Demon Elbow": {
    name: "Demon Elbow",
    desc_pt: "Passe sorrateiramente por um alvo que esteja se preparando para atacar e acerte-o com uma cotovelada devastadora. Falha se o alvo não tiver usado uma habilidade ativa.",
    desc_en: "Sneak past a target preparing an attack and hit them with a punishing elbow. Fails if the target did not use an active skill.",
    type: "demon",
    attack: "physical",
    power: 70,
    accuracy: 0,
  },
  "Limb Regrowth": {
    name: "Limb Regrowth",
    desc_pt: "[002]Recupera 30%[000] da sua vida e remove o veneno. Falha se você estiver com a vida cheia.",
    desc_en: "[002]Heal 30%[000] of your HP and remove poison. Fails if you are full health.",
    type: "nature",
    attack: "status",
    power: 0,
    accuracy: 0,
  },
  "Angry Explosion": {
    name: "Angry Explosion",
    desc_pt: "Libere sua raiva em uma explosão, que dobra de poder se você estiver afetado por uma condição de status.",
    desc_en: "Release your anger in an explosion, doubling in power if you are affected by a status condition.",
    type: "psychic",
    attack: "special",
    power: 50,
    accuracy: 100,
  },
  "Rest": {
    name: "Rest",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 0,
  },
  "Candy Beam": {
    name: "Candy Beam",
    desc_pt: "Transforme o inimigo em doce. Ele ficará incapacitado por dois turnos; se o usuário o derrotar, [002]recuperará 20% de HP[000].",
    desc_en: "Turn the enemy into candy. They are disabled for two turns, if the user defeats them [002]heal 20% HP[000].",
    type: "psychic",
    attack: "status",
    power: 0,
    accuracy: 80,
    pp: 8,
  },
  "Psychic Blast": {
    name: "Psychic Blast",
    desc_pt: "Atire uma pedra no seu inimigo! Use seus poderes psíquicos.",
    desc_en: "Throw a rock at your Enemy! Using your psychic prowess.",
    type: "psychic",
    attack: "special",
    power: 40,
    accuracy: 100,
  },
  "Energy Charge": {
    name: "Energy Charge",
    desc_pt: "Aumenta o [002]SP.ATK [+1][000] ou o [002]ATK [+1][000]. [004](Dependendo de qual for maior)[000]",
    desc_en: "Raises [002]SP.ATK [+1][000] or [002]ATK [+1][000]. [004](Depending on which is higher)[000]",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 0,
  },
  "Rubber Balloon": {
    name: "Rubber Balloon",
    desc_pt: "Infle-se para aumentar a [002]DEF [+1][000].",
    desc_en: "Inflate yourself to increase [002]DEF [+1][000].",
    type: "neutral",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Punch": {
    name: "Punch",
    desc_pt: "Uma técnica básica de combate corpo a corpo que desfere um golpe poderoso e rápido usando o punho.",
    desc_en: "A basic melee combat technique that delivers a powerful and swift strike using one's fist.",
    type: "neutral",
    attack: "physical",
    power: 35,
    accuracy: 100,
  },
  "Rapid Punches": {
    name: "Rapid Punches",
    desc_pt: "Aprimore seu oponente com os punhos até conseguir um bom golpe. Aumenta a chance de acerto crítico.",
    desc_en: "Better your opponent with fists until you get a good one in. Increased chance to crit.",
    type: "neutral",
    attack: "physical",
    power: 35,
    accuracy: 100,
  },
  "Rubber Pistol": {
    name: "Rubber Pistol",
    desc_pt: "Um soco potente como uma pistola, com um alcance incrível!",
    desc_en: "A pistol-like punch that has insane reach!",
    type: "fighting",
    attack: "physical",
    power: 35,
    accuracy: 100,
  },
  "Fighting Spirit": {
    name: "Fighting Spirit",
    desc_pt: "Prepare-se para a luta e concentre sua força interior, aumentando [002]SP.DEF [+1][000] e [002]ATK [+1][000].",
    desc_en: "Ready yourself for the fight and focus your inner strength, increasing [002]SP.DEF [+1][000] and [002]ATK [+1][000].",
    type: "fighting",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Bazooka": {
    name: "Bazooka",
    desc_pt: "Arremesse seu oponente para longe com força, usando as duas palmas das mãos.",
    desc_en: "Blast your opponent away on impact with two forceful palms.",
    type: "fighting",
    attack: "physical",
    power: 65,
    accuracy: 90,
  },
  "Phase Two": {
    name: "Phase Two",
    desc_pt: "Prepare-se e aqueça-se para a transformação. Aprimora as técnicas de atributos de borracha.[004](Após selecionar o Phase Two, pode usar outro movimento novamente)[000]",
    desc_en: "Pump up and become hot-blooded to transform. Upgrades rubber-attribute techniques.[004](After selecting Phase Two, you can use another move again)[000]",
    type: "fighting",
    attack: "status",
    power: 0,
    accuracy: 100,
    pp: 2,
    moveTrigger: [{ move:"Armament", trade:"Red Talon" }, { move:"Bazooka", trade:"Jet Bullet"}],
  },
  "Headbutt": {
    name: "Headbutt",
    type: "neutral",
    attack: "physical",
  },
  "Armament": {
    name: "Armament",
    desc_pt: "Vista-se com uma armadura preta para aumentar seu [002]ATK [+1][000] e permitir que você acerte inimigos intangíveis.",
    desc_en: "Coat yourself in a armor black to increase your [002]ATK [+1][000] and allow you to hit intangible enemies.",
    type: "fighting",
    attack: "status",
    power: 0,
    accuracy: 100,
  },
  "Energy Blast": {
    name: "Energy Blast",
    desc_pt: "Dispare uma rajada de energia contra o inimigo, causando dano!",
    desc_en: "Fire a blast of energy at the enemy dealing damage!",
    type: "neutral",
    attack: "special",
    power: 25,
    accuracy: 100,
  }
};